# Generated by Django 4.1.7 on 2023-07-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Created', 'Created'), ('Ready', 'Ready'), ('Completed', 'Completed'), ('Archived', 'Archived')], max_length=100)),
                ('order_number', models.IntegerField()),
            ],
        ),
    ]
